=== mjkelly/campusmap/data/locations.dtd
<!--
	Descripton of the location data type. All location input files must
	conform to this DTD. The editor's behavior on invalid input is not
	defined.
-->

<!ELEMENT locations (location+)>
<!ATTLIST locations version CDATA #REQUIRED>

<!ELEMENT location (name, aliases?, keywords?, code?)>
<!ATTLIST location x CDATA #REQUIRED>
<!ATTLIST location y CDATA #REQUIRED>
<!ATTLIST location id CDATA #REQUIRED>
<!ATTLIST location passThrough (true|false) #REQUIRED>
<!ATTLIST location intersect (true|false) #REQUIRED>
<!ATTLIST location displayName (true|false) #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT aliases (alias+)>
<!ELEMENT alias (#PCDATA)>
<!ELEMENT keywords (#PCDATA)>
<!ELEMENT code (#PCDATA)>

<!-- eof -->

=== mjkelly/campusmap/data/rawLocations.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE locations SYSTEM 'locations.dtd'>

<locations version="1.0">
	<location x="4898" y="4085" id="1" passThrough="false" intersect="true" displayName="true">
		<name>201 University Center</name>
	</location>
	<location x="4843" y="4162" id="2" passThrough="false" intersect="true" displayName="true">
		<name>202 University Center</name>
	</location>
	<location x="4732" y="3922" id="3" passThrough="false" intersect="true" displayName="true">
		<name>214 University Center</name>
		<aliases>
			<alias>Chancellor&apos;s Complex 214</alias>
			<alias>Academic Senate</alias>
		</aliases>
	</location>
	<location x="4736" y="3880" id="4" passThrough="false" intersect="true" displayName="true">
		<name>215 University Center</name>
		<aliases>
			<alias>215 Chancellor&apos;s Complex</alias>
		</aliases>
	</location>
	<location x="5037" y="4110" id="5" passThrough="false" intersect="true" displayName="true">
		<name>301 University Ctr</name>
		<aliases>
			<alias>Registrar</alias>
			<alias>University Center 301</alias>
		</aliases>
	</location>
	<location x="5092" y="4089" id="6" passThrough="false" intersect="true" displayName="true">
		<name>301A University Center</name>
	</location>
	<location x="5168" y="4025" id="7" passThrough="false" intersect="true" displayName="true">
		<name>302 University Center</name>
	</location>
	<location x="5172" y="4169" id="8" passThrough="false" intersect="true" displayName="true">
		<name>Cancer Research Facility</name>
		<aliases>
			<alias>303 University Center</alias>
		</aliases>
	</location>
	<location x="5329" y="4043" id="9" passThrough="false" intersect="true" displayName="true">
		<name>309 University Ctr</name>
		<aliases>
			<alias>University Center 309</alias>
		</aliases>
	</location>
	<location x="5280" y="4007" id="10" passThrough="false" intersect="true" displayName="true">
		<name>310 University Center</name>
		<aliases>
			<alias>Housing and Dining Services</alias>
		</aliases>
	</location>
	<location x="7855" y="4808" id="11" passThrough="false" intersect="true" displayName="true">
		<name>3803 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3803</alias>
		</aliases>
	</location>
	<location x="7885" y="4930" id="12" passThrough="false" intersect="true" displayName="true">
		<name>3811 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3811</alias>
		</aliases>
	</location>
	<location x="7934" y="4817" id="13" passThrough="false" intersect="true" displayName="true">
		<name>3819 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3819</alias>
		</aliases>
	</location>
	<location x="7977" y="4946" id="14" passThrough="false" intersect="true" displayName="true">
		<name>3827 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3827</alias>
		</aliases>
	</location>
	<location x="8003" y="4792" id="15" passThrough="false" intersect="true" displayName="true">
		<name>3835 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3835</alias>
		</aliases>
	</location>
	<location x="8069" y="4975" id="16" passThrough="false" intersect="true" displayName="true">
		<name>3843 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3843</alias>
		</aliases>
	</location>
	<location x="8070" y="4833" id="17" passThrough="false" intersect="true" displayName="true">
		<name>3851 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3851</alias>
		</aliases>
	</location>
	<location x="8132" y="4938" id="18" passThrough="false" intersect="true" displayName="true">
		<name>3859 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3859</alias>
		</aliases>
	</location>
	<location x="8150" y="4845" id="19" passThrough="false" intersect="true" displayName="true">
		<name>3867 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3867</alias>
		</aliases>
	</location>
	<location x="8210" y="4794" id="20" passThrough="false" intersect="true" displayName="true">
		<name>3875 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3875</alias>
		</aliases>
	</location>
	<location x="8228" y="4929" id="21" passThrough="false" intersect="true" displayName="true">
		<name>3883 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3883</alias>
		</aliases>
	</location>
	<location x="8274" y="4851" id="22" passThrough="false" intersect="true" displayName="true">
		<name>3891 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3891</alias>
		</aliases>
	</location>
	<location x="8331" y="4794" id="23" passThrough="false" intersect="true" displayName="true">
		<name>3899 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3899</alias>
		</aliases>
	</location>
	<location x="8372" y="4921" id="24" passThrough="false" intersect="true" displayName="true">
		<name>3903 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3903</alias>
		</aliases>
	</location>
	<location x="8410" y="4837" id="25" passThrough="false" intersect="true" displayName="true">
		<name>3911 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3911</alias>
		</aliases>
	</location>
	<location x="8436" y="4970" id="26" passThrough="false" intersect="true" displayName="true">
		<name>3919 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3919</alias>
		</aliases>
	</location>
	<location x="8474" y="4821" id="27" passThrough="false" intersect="true" displayName="true">
		<name>3927 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3927</alias>
		</aliases>
	</location>
	<location x="8525" y="5007" id="28" passThrough="false" intersect="true" displayName="true">
		<name>3935 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3935</alias>
		</aliases>
	</location>
	<location x="8524" y="4876" id="29" passThrough="false" intersect="true" displayName="true">
		<name>3943 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3943</alias>
		</aliases>
	</location>
	<location x="8587" y="4950" id="30" passThrough="false" intersect="true" displayName="true">
		<name>3951 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3951</alias>
		</aliases>
	</location>
	<location x="8603" y="4846" id="31" passThrough="false" intersect="true" displayName="true">
		<name>3959 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3959</alias>
		</aliases>
	</location>
	<location x="8661" y="4942" id="32" passThrough="false" intersect="true" displayName="true">
		<name>3967 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3967</alias>
		</aliases>
	</location>
	<location x="8695" y="5015" id="33" passThrough="false" intersect="true" displayName="true">
		<name>3975 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3975</alias>
		</aliases>
	</location>
	<location x="8703" y="4872" id="34" passThrough="false" intersect="true" displayName="true">
		<name>3983 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3983</alias>
		</aliases>
	</location>
	<location x="8761" y="5044" id="35" passThrough="false" intersect="true" displayName="true">
		<name>3991 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3991</alias>
		</aliases>
	</location>
	<location x="8760" y="4926" id="36" passThrough="false" intersect="true" displayName="true">
		<name>3999 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 3999</alias>
		</aliases>
	</location>
	<location x="5003" y="3983" id="37" passThrough="false" intersect="true" displayName="true">
		<name>400 University Center</name>
	</location>
	<location x="5037" y="3963" id="38" passThrough="false" intersect="true" displayName="true">
		<name>401 University Center</name>
	</location>
	<location x="8865" y="5024" id="39" passThrough="false" intersect="true" displayName="true">
		<name>4043 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 4043</alias>
		</aliases>
	</location>
	<location x="8893" y="5107" id="40" passThrough="false" intersect="true" displayName="true">
		<name>4051 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 4051</alias>
		</aliases>
	</location>
	<location x="8904" y="4949" id="41" passThrough="false" intersect="true" displayName="true">
		<name>4059 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 4059</alias>
		</aliases>
	</location>
	<location x="8950" y="5160" id="42" passThrough="false" intersect="true" displayName="true">
		<name>4067 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 4067</alias>
		</aliases>
	</location>
	<location x="8962" y="5010" id="43" passThrough="false" intersect="true" displayName="true">
		<name>4075 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 4075</alias>
		</aliases>
	</location>
	<location x="9017" y="5136" id="44" passThrough="false" intersect="true" displayName="true">
		<name>4083 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 4083</alias>
		</aliases>
	</location>
	<location x="5334" y="3720" id="45" passThrough="false" intersect="true" displayName="true">
		<name>409 University Center (Construction)</name>
	</location>
	<location x="9027" y="4986" id="46" passThrough="false" intersect="true" displayName="true">
		<name>4091 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 4091</alias>
		</aliases>
	</location>
	<location x="9066" y="5059" id="47" passThrough="false" intersect="true" displayName="true">
		<name>4099 Mesa Housing</name>
		<aliases>
			<alias>Mesa Housing North - 4099</alias>
		</aliases>
	</location>
	<location x="5274" y="3909" id="48" passThrough="false" intersect="true" displayName="true">
		<name>413 University Center (Construction)</name>
	</location>
	<location x="5082" y="3536" id="50" passThrough="false" intersect="true" displayName="true">
		<name>501B University Center</name>
	</location>
	<location x="5085" y="3640" id="51" passThrough="false" intersect="true" displayName="true">
